
import 'package:flutter/material.dart';
import 'package:sensors/sensors.dart';
import 'dart:math' as math;

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  double _force = 0;
  double _angle = 0;

  @override
  void initState() {
    super.initState();
    accelerometerEvents.listen((AccelerometerEvent event) {
      // Calculate the force generated by swinging the phone
      double acceleration = math.sqrt(
          math.pow(event.x, 2) + math.pow(event.y, 2) + math.pow(event.z, 2));
      double mass = 0.2;
      // assume the mass of the phone is 200g
      setState(() {
        _force = mass * acceleration;
        print('------'+_force.toStringAsFixed(2));

      });
    });
    gyroscopeEvents.listen((GyroscopeEvent event) {
      // Calculate the rotation angle generated by swinging the phone
      setState(() {

        _angle += event.z;


      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        backgroundColor: Colors.white,
        appBar: AppBar(
          title: Text('Tennis Racket'),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Text(
                'Force: ${_force.toStringAsFixed(2)}',
                style: TextStyle(fontSize: 24, color: Colors.blue),
              ),
              Text(
                'Rotation Angle: ${_angle.toStringAsFixed(3)}',
                style: TextStyle(fontSize: 24,  color: Colors.blue),
              ),
            ],
          ),
        ),
      ),
    );
  }
}